spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://89.191.229.77:5432/default_db
    username: gen_user
    password: QBh7Dl1qkcY
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  jpa:
    showSql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database: postgresql

auth:
  expiredTimeInSec: 1234567890
