### получение цен
GET http://89.191.229.11:8080/api/v1/coins/prices

### получение цен по конкретной монете
GET http://89.191.229.11:8080/api/v1/coins/prices/ETH?interval=3m

### получение статистики по монете
GET http://89.191.229.11:8080/api/v1/statistics/leaderboard

### получение статистики по монете
GET http://89.191.229.11:8080/api/v1/balance/info
token: 000

### регистрация
POST http://localhost:8080/api/v1/auth/registration
content-type: application/json

{
  "login": "testLogin123",
  "password": "qwerty123"
}

### создание заказа на покупку
POST http://localhost:8080/api/v1/orders/create
content-type: application/json
token: 14c42671-3503-4126-953c-ad1f2f7985d3

{
  "assetsSymbol": "BTC",
  "usdMoney": 5
}

### создание заказа на продажу
POST http://localhost:8080/api/v1/orders/sail/all
content-type: application/json
token: 14c42671-3503-4126-953c-ad1f2f7985d3

{
  "assetsSymbol": "BTC"
}

